        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:10 2017
        MODULE ACCRETE_SINK__genmod
          INTERFACE 
            SUBROUTINE ACCRETE_SINK(IND_GRID,IND_PART,IND_GRID_PART,NG, &
     &NP,ILEVEL,ON_CREATION)
              INTEGER(KIND=4) :: IND_GRID(1:)
              INTEGER(KIND=4) :: IND_PART(1:)
              INTEGER(KIND=4) :: IND_GRID_PART(1:)
              INTEGER(KIND=4) :: NG
              INTEGER(KIND=4) :: NP
              INTEGER(KIND=4) :: ILEVEL
              LOGICAL(KIND=4) :: ON_CREATION
            END SUBROUTINE ACCRETE_SINK
          END INTERFACE 
        END MODULE ACCRETE_SINK__genmod
