        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:45 2017
        MODULE ADAPTIVE_LOOP__genmod
          INTERFACE 
            SUBROUTINE ADAPTIVE_LOOP
            END SUBROUTINE ADAPTIVE_LOOP
          END INTERFACE 
        END MODULE ADAPTIVE_LOOP__genmod
