        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:20 2017
        MODULE ADAPTIVE_RT_C_UPDATE__genmod
          INTERFACE 
            SUBROUTINE ADAPTIVE_RT_C_UPDATE(ILEVEL,DT)
              INTEGER(KIND=4) :: ILEVEL
              REAL(KIND=8) :: DT
            END SUBROUTINE ADAPTIVE_RT_C_UPDATE
          END INTERFACE 
        END MODULE ADAPTIVE_RT_C_UPDATE__genmod
