        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:08 2017
        MODULE ADD_FREE_COND__genmod
          INTERFACE 
            SUBROUTINE ADD_FREE_COND(IND_PART,OK,NP)
              INTEGER(KIND=4) :: IND_PART(1:)
              LOGICAL(KIND=4) :: OK(1:)
              INTEGER(KIND=4) :: NP
            END SUBROUTINE ADD_FREE_COND
          END INTERFACE 
        END MODULE ADD_FREE_COND__genmod
