        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE ALLOCATE_PEAK_PATCH_ARRAYS__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_PEAK_PATCH_ARRAYS
            END SUBROUTINE ALLOCATE_PEAK_PATCH_ARRAYS
          END INTERFACE 
        END MODULE ALLOCATE_PEAK_PATCH_ARRAYS__genmod
