        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:45 2017
        MODULE AMR_STEP__genmod
          INTERFACE 
            RECURSIVE SUBROUTINE AMR_STEP(ILEVEL,ICOUNT)
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: ICOUNT
            END SUBROUTINE AMR_STEP
          END INTERFACE 
        END MODULE AMR_STEP__genmod
