        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE ANALYZE_PEAK_MEMORY__genmod
          INTERFACE 
            SUBROUTINE ANALYZE_PEAK_MEMORY
              USE AMR_COMMONS
            END SUBROUTINE ANALYZE_PEAK_MEMORY
          END INTERFACE 
        END MODULE ANALYZE_PEAK_MEMORY__genmod
