        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:49 2017
        MODULE ANGULAR_DECOMPOSITION_CENTER__genmod
          INTERFACE 
            SUBROUTINE ANGULAR_DECOMPOSITION_CENTER
            END SUBROUTINE ANGULAR_DECOMPOSITION_CENTER
          END INTERFACE 
        END MODULE ANGULAR_DECOMPOSITION_CENTER__genmod
