        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:47 2017
        MODULE AUTHORIZE_FINE__genmod
          INTERFACE 
            SUBROUTINE AUTHORIZE_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE AUTHORIZE_FINE
          END INTERFACE 
        END MODULE AUTHORIZE_FINE__genmod
