        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:47 2017
        MODULE AUTHORIZE_COARSE__genmod
          INTERFACE 
            SUBROUTINE AUTHORIZE_COARSE
            END SUBROUTINE AUTHORIZE_COARSE
          END INTERFACE 
        END MODULE AUTHORIZE_COARSE__genmod
