        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:15 2017
        MODULE BACKUP_STELLAR__genmod
          INTERFACE 
            SUBROUTINE BACKUP_STELLAR(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE BACKUP_STELLAR
          END INTERFACE 
        END MODULE BACKUP_STELLAR__genmod
