        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:14 2017
        MODULE BACKUP_SINK__genmod
          INTERFACE 
            SUBROUTINE BACKUP_SINK(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE BACKUP_SINK
          END INTERFACE 
        END MODULE BACKUP_SINK__genmod
