        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE BACKUP_AMR__genmod
          INTERFACE 
            SUBROUTINE BACKUP_AMR(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE BACKUP_AMR
          END INTERFACE 
        END MODULE BACKUP_AMR__genmod
