        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:50 2017
        MODULE BAROTROP1D__genmod
          INTERFACE 
            FUNCTION BAROTROP1D(RHON)
              REAL(KIND=8) :: RHON
              REAL(KIND=8) :: BAROTROP1D
            END FUNCTION BAROTROP1D
          END INTERFACE 
        END MODULE BAROTROP1D__genmod
