        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:43 2017
        MODULE BOUNDARY_FRIG__genmod
          INTERFACE 
            SUBROUTINE BOUNDARY_FRIG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE BOUNDARY_FRIG
          END INTERFACE 
        END MODULE BOUNDARY_FRIG__genmod
