        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE BOUNDARY_PEAK_DP__genmod
          INTERFACE 
            SUBROUTINE BOUNDARY_PEAK_DP(XX)
              USE CLFIND_COMMONS
              USE AMR_COMMONS
              REAL(KIND=8) :: XX(1:NPEAKS_MAX)
            END SUBROUTINE BOUNDARY_PEAK_DP
          END INTERFACE 
        END MODULE BOUNDARY_PEAK_DP__genmod
