        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE BUILD_PEAK_COMMUNICATOR__genmod
          INTERFACE 
            SUBROUTINE BUILD_PEAK_COMMUNICATOR
              USE AMR_COMMONS
            END SUBROUTINE BUILD_PEAK_COMMUNICATOR
          END INTERFACE 
        END MODULE BUILD_PEAK_COMMUNICATOR__genmod
