        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:20 2017
        MODULE CALC_EQUILIBRIUM_XION__genmod
          INTERFACE 
            SUBROUTINE CALC_EQUILIBRIUM_XION(VARS,RTVARS,XION)
              REAL(KIND=8) :: VARS(12)
              REAL(KIND=8) :: RTVARS(12)
              REAL(KIND=8) :: XION(3)
            END SUBROUTINE CALC_EQUILIBRIUM_XION
          END INTERFACE 
        END MODULE CALC_EQUILIBRIUM_XION__genmod
