        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:05 2017
        MODULE CIC_FROM_MULTIPOLE__genmod
          INTERFACE 
            SUBROUTINE CIC_FROM_MULTIPOLE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE CIC_FROM_MULTIPOLE
          END INTERFACE 
        END MODULE CIC_FROM_MULTIPOLE__genmod
