        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:05 2017
        MODULE CIC_CELL__genmod
          INTERFACE 
            SUBROUTINE CIC_CELL(IND_GRID,NGRID,ILEVEL)
              INTEGER(KIND=4) :: IND_GRID(1:)
              INTEGER(KIND=4) :: NGRID
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE CIC_CELL
          END INTERFACE 
        END MODULE CIC_CELL__genmod
