        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:17 2017
        MODULE CLEANUP_MG_LEVEL__genmod
          INTERFACE 
            SUBROUTINE CLEANUP_MG_LEVEL(ILEVEL)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
            END SUBROUTINE CLEANUP_MG_LEVEL
          END INTERFACE 
        END MODULE CLEANUP_MG_LEVEL__genmod
