        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:45 2017
        MODULE CLEAN_STOP__genmod
          INTERFACE 
            SUBROUTINE CLEAN_STOP
            END SUBROUTINE CLEAN_STOP
          END INTERFACE 
        END MODULE CLEAN_STOP__genmod
