        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:02 2017
        MODULE CMP_ENERGY_CR__genmod
          INTERFACE 
            SUBROUTINE CMP_ENERGY_CR(ETYPE)
              INTEGER(KIND=4), INTENT(IN) :: ETYPE
            END SUBROUTINE CMP_ENERGY_CR
          END INTERFACE 
        END MODULE CMP_ENERGY_CR__genmod
