        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:50 2017
        MODULE CMP_EDDINGTON_TENSOR__genmod
          INTERFACE 
            SUBROUTINE CMP_EDDINGTON_TENSOR(NPC,FP,T_EDD)
              REAL(KIND=8) :: NPC
              REAL(KIND=8) :: FP(1:)
              REAL(KIND=8) :: T_EDD(1:,1:)
            END SUBROUTINE CMP_EDDINGTON_TENSOR
          END INTERFACE 
        END MODULE CMP_EDDINGTON_TENSOR__genmod
