        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:18 2017
        MODULE CMP_RESIDUAL_MG_COARSE__genmod
          INTERFACE 
            SUBROUTINE CMP_RESIDUAL_MG_COARSE(ILEVEL)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
            END SUBROUTINE CMP_RESIDUAL_MG_COARSE
          END INTERFACE 
        END MODULE CMP_RESIDUAL_MG_COARSE__genmod
