        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:20 2017
        MODULE CMP_EQUILIBRIUM_ABUNDANCES__genmod
          INTERFACE 
            SUBROUTINE CMP_EQUILIBRIUM_ABUNDANCES(T2,NH,PHI_RATES,MU,   &
     &NSPEC)
              REAL(KIND=8) :: T2
              REAL(KIND=8) :: NH
              REAL(KIND=8) :: PHI_RATES(3)
              REAL(KIND=8) :: MU
              REAL(KIND=8) :: NSPEC(1:)
            END SUBROUTINE CMP_EQUILIBRIUM_ABUNDANCES
          END INTERFACE 
        END MODULE CMP_EQUILIBRIUM_ABUNDANCES__genmod
