        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:49 2017
        MODULE CMP_MINMAXORDER__genmod
          INTERFACE 
            SUBROUTINE CMP_MINMAXORDER(X,ORDER_MIN,ORDER_MAX,DX,NN)
              REAL(KIND=8) :: X(1:,1:)
              REAL(KIND=8) :: ORDER_MIN(1:)
              REAL(KIND=8) :: ORDER_MAX(1:)
              REAL(KIND=8) :: DX
              INTEGER(KIND=4) :: NN
            END SUBROUTINE CMP_MINMAXORDER
          END INTERFACE 
        END MODULE CMP_MINMAXORDER__genmod
