        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:49 2017
        MODULE CMP_NEW_CPU_MAP__genmod
          INTERFACE 
            SUBROUTINE CMP_NEW_CPU_MAP
              USE AMR_COMMONS
            END SUBROUTINE CMP_NEW_CPU_MAP
          END INTERFACE 
        END MODULE CMP_NEW_CPU_MAP__genmod
