        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:00 2017
        MODULE CMP_ENERGY__genmod
          INTERFACE 
            SUBROUTINE CMP_ENERGY(ETYPE)
              INTEGER(KIND=4), INTENT(IN) :: ETYPE
            END SUBROUTINE CMP_ENERGY
          END INTERFACE 
        END MODULE CMP_ENERGY__genmod
