        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:18 2017
        MODULE CMP_RESIDUAL_NORM2_FINE__genmod
          INTERFACE 
            SUBROUTINE CMP_RESIDUAL_NORM2_FINE(ILEVEL,NORM2)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
              REAL(KIND=8), INTENT(OUT) :: NORM2
            END SUBROUTINE CMP_RESIDUAL_NORM2_FINE
          END INTERFACE 
        END MODULE CMP_RESIDUAL_NORM2_FINE__genmod
