        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:16 2017
        MODULE CMP_AP_CG__genmod
          INTERFACE 
            SUBROUTINE CMP_AP_CG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE CMP_AP_CG
          END INTERFACE 
        END MODULE CMP_AP_CG__genmod
