        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:17 2017
        MODULE CMP_RESIDUAL_MG__genmod
          INTERFACE 
            SUBROUTINE CMP_RESIDUAL_MG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE CMP_RESIDUAL_MG
          END INTERFACE 
        END MODULE CMP_RESIDUAL_MG__genmod
