        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:02 2017
        MODULE CMP_MATRIXA_CRDIFFUSION__genmod
          INTERFACE 
            SUBROUTINE CMP_MATRIXA_CRDIFFUSION(ILEVEL,NSUB,COMPUTE,     &
     &IGROUP)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
              INTEGER(KIND=4), INTENT(IN) :: NSUB
              INTEGER(KIND=4), INTENT(IN) :: COMPUTE
              INTEGER(KIND=4), INTENT(IN) :: IGROUP
            END SUBROUTINE CMP_MATRIXA_CRDIFFUSION
          END INTERFACE 
        END MODULE CMP_MATRIXA_CRDIFFUSION__genmod
