        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:10 2017
        MODULE COLLECT_ACCZONE_AVG__genmod
          INTERFACE 
            SUBROUTINE COLLECT_ACCZONE_AVG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE COLLECT_ACCZONE_AVG
          END INTERFACE 
        END MODULE COLLECT_ACCZONE_AVG__genmod
