        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:10 2017
        MODULE COLLECT_ACCZONE_AVG_NP__genmod
          INTERFACE 
            SUBROUTINE COLLECT_ACCZONE_AVG_NP(IND_GRID,IND_PART,        &
     &IND_GRID_PART,NG,NP,ILEVEL)
              INTEGER(KIND=4) :: IND_GRID(1:)
              INTEGER(KIND=4) :: IND_PART(1:)
              INTEGER(KIND=4) :: IND_GRID_PART(1:)
              INTEGER(KIND=4) :: NG
              INTEGER(KIND=4) :: NP
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE COLLECT_ACCZONE_AVG_NP
          END INTERFACE 
        END MODULE COLLECT_ACCZONE_AVG_NP__genmod
