        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:01 2017
        MODULE COLUMN_DENSITY__genmod
          INTERFACE 
            SUBROUTINE COLUMN_DENSITY(IND_GRID,NGRID,ILEVEL,COLUMN_DENS,&
     &H2COLUMN_DENS)
              USE AMR_COMMONS
              INTEGER(KIND=4) :: NGRID
              INTEGER(KIND=4) :: IND_GRID(1:)
              INTEGER(KIND=4) :: ILEVEL
              REAL(KIND=8) :: COLUMN_DENS(1:,1:NDIREXT_M,1:NDIREXT_N)
              REAL(KIND=8) :: H2COLUMN_DENS(1:,1:NDIREXT_M,1:NDIREXT_N)
            END SUBROUTINE COLUMN_DENSITY
          END INTERFACE 
        END MODULE COLUMN_DENSITY__genmod
