        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:00 2017
        MODULE COMPUTE_VALP__genmod
          INTERFACE 
            SUBROUTINE COMPUTE_VALP
            END SUBROUTINE COMPUTE_VALP
          END INTERFACE 
        END MODULE COMPUTE_VALP__genmod
