        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:14 2017
        MODULE COMPUTE_NCLOUD_SINK__genmod
          INTERFACE 
            SUBROUTINE COMPUTE_NCLOUD_SINK
            END SUBROUTINE COMPUTE_NCLOUD_SINK
          END INTERFACE 
        END MODULE COMPUTE_NCLOUD_SINK__genmod
