        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:00 2017
        MODULE COMPUTE_RESIDUAL_IN_CELL__genmod
          INTERFACE 
            SUBROUTINE COMPUTE_RESIDUAL_IN_CELL(I,VOL_LOC,RESIDUAL,     &
     &MAT_RESIDUAL)
              INTEGER(KIND=4), INTENT(IN) :: I
              REAL(KIND=8), INTENT(IN) :: VOL_LOC
              REAL(KIND=8), INTENT(OUT) :: RESIDUAL(0)
              REAL(KIND=8), INTENT(OUT) :: MAT_RESIDUAL(0,0)
            END SUBROUTINE COMPUTE_RESIDUAL_IN_CELL
          END INTERFACE 
        END MODULE COMPUTE_RESIDUAL_IN_CELL__genmod
