        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:09 2017
        MODULE COMPUTE_ACCRETION_RATE__genmod
          INTERFACE 
            SUBROUTINE COMPUTE_ACCRETION_RATE(WRITE_SINKS)
              USE PM_COMMONS
              LOGICAL(KIND=4) :: WRITE_SINKS
            END SUBROUTINE COMPUTE_ACCRETION_RATE
          END INTERFACE 
        END MODULE COMPUTE_ACCRETION_RATE__genmod
