        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:03 2017
        MODULE COMPUTE_1D_TVD_COND__genmod
          INTERFACE 
            SUBROUTINE COMPUTE_1D_TVD_COND(B,S,NN)
              REAL(KIND=8) :: B(1:,0:)
              REAL(KIND=8) :: S(1:,1:)
              INTEGER(KIND=4) :: NN
            END SUBROUTINE COMPUTE_1D_TVD_COND
          END INTERFACE 
        END MODULE COMPUTE_1D_TVD_COND__genmod
