        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE COMPUTE_CLUMP_PROPERTIES_ROUND2__genmod
          INTERFACE 
            SUBROUTINE COMPUTE_CLUMP_PROPERTIES_ROUND2
              USE RT_COOLING_MODULE, ONLY :                             &
     &          KAPPASC
              USE CLFIND_COMMONS
            END SUBROUTINE COMPUTE_CLUMP_PROPERTIES_ROUND2
          END INTERFACE 
        END MODULE COMPUTE_CLUMP_PROPERTIES_ROUND2__genmod
