        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:57 2017
        MODULE COMPUTE_CENTRAL__genmod
          INTERFACE 
            SUBROUTINE COMPUTE_CENTRAL(A,W,NN)
              REAL(KIND=8) :: A(1:,0:)
              REAL(KIND=8) :: W(1:,1:)
              INTEGER(KIND=4) :: NN
            END SUBROUTINE COMPUTE_CENTRAL
          END INTERFACE 
        END MODULE COMPUTE_CENTRAL__genmod
