        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:01 2017
        MODULE CONTRIBUTION__genmod
          INTERFACE 
            SUBROUTINE CONTRIBUTION(IND_GRID,NGRID,ILEVEL,IL,IND_LIM1,  &
     &IND_LIM2,COLUMN_DENS,H2COLUMN_DENS)
              USE AMR_COMMONS
              INTEGER(KIND=4), INTENT(IN) :: NGRID
              INTEGER(KIND=4) :: IND_GRID(1:)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
              INTEGER(KIND=4), INTENT(IN) :: IL
              INTEGER(KIND=4), INTENT(IN) :: IND_LIM1(1:NGRID,1:)
              INTEGER(KIND=4), INTENT(IN) :: IND_LIM2(1:NGRID,1:)
              REAL(KIND=8), INTENT(INOUT) :: COLUMN_DENS(1:,1:NDIREXT_M,&
     &1:NDIREXT_N)
              REAL(KIND=8), INTENT(INOUT) :: H2COLUMN_DENS(1:,1:        &
     &NDIREXT_M,1:NDIREXT_N)
            END SUBROUTINE CONTRIBUTION
          END INTERFACE 
        END MODULE CONTRIBUTION__genmod
