        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:50 2017
        MODULE COOLING_FINE__genmod
          INTERFACE 
            SUBROUTINE COOLING_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE COOLING_FINE
          END INTERFACE 
        END MODULE COOLING_FINE__genmod
