        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:50 2017
        MODULE COOLFINE1__genmod
          INTERFACE 
            SUBROUTINE COOLFINE1(IND_GRID,NGRID,ILEVEL)
              USE RT_HYDRO_COMMONS
              INTEGER(KIND=4) :: IND_GRID(1:)
              INTEGER(KIND=4) :: NGRID
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE COOLFINE1
          END INTERFACE 
        END MODULE COOLFINE1__genmod
