        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:50 2017
        MODULE COORD_DISTANCE__genmod
          INTERFACE 
            FUNCTION COORD_DISTANCE(ZZ,OMEGA0,OMEGAL,OMEGAR,COVERH0)
              REAL(KIND=8) :: ZZ
              REAL(KIND=8) :: OMEGA0
              REAL(KIND=8) :: OMEGAL
              REAL(KIND=8) :: OMEGAR
              REAL(KIND=8) :: COVERH0
              REAL(KIND=8) :: COORD_DISTANCE
            END FUNCTION COORD_DISTANCE
          END INTERFACE 
        END MODULE COORD_DISTANCE__genmod
