        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:10 2017
        MODULE COUNT_CLOUDS_NP__genmod
          INTERFACE 
            SUBROUTINE COUNT_CLOUDS_NP(IND_GRID,IND_PART,IND_GRID_PART, &
     &NG,NP,ACTION,ILEVEL)
              INTEGER(KIND=4) :: IND_GRID(1:)
              INTEGER(KIND=4) :: IND_PART(1:)
              INTEGER(KIND=4) :: IND_GRID_PART(1:)
              INTEGER(KIND=4) :: NG
              INTEGER(KIND=4) :: NP
              CHARACTER(LEN=15) :: ACTION
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE COUNT_CLOUDS_NP
          END INTERFACE 
        END MODULE COUNT_CLOUDS_NP__genmod
