        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:12 2017
        MODULE COUNT_TEST_PARTICLE__genmod
          INTERFACE 
            SUBROUTINE COUNT_TEST_PARTICLE(XX,ILEVEL,NSKIP,ACTION)
              USE AMR_COMMONS
              REAL(KIND=8) :: XX(1:NCOARSE+NGRIDMAX*8)
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: NSKIP
              INTEGER(KIND=4) :: ACTION
            END SUBROUTINE COUNT_TEST_PARTICLE
          END INTERFACE 
        END MODULE COUNT_TEST_PARTICLE__genmod
