        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE COUNT_NBORS__genmod
          INTERFACE 
            SUBROUTINE COUNT_NBORS(IGRIDN,IND,N_NBOR,NN)
              INTEGER(KIND=4) :: IGRIDN(1:,0:)
              INTEGER(KIND=4) :: IND
              INTEGER(KIND=4) :: N_NBOR
              INTEGER(KIND=4) :: NN
            END SUBROUTINE COUNT_NBORS
          END INTERFACE 
        END MODULE COUNT_NBORS__genmod
