        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:10 2017
        MODULE COUNT_PARTS__genmod
          INTERFACE 
            SUBROUTINE COUNT_PARTS
              USE PM_COMMONS
            END SUBROUTINE COUNT_PARTS
          END INTERFACE 
        END MODULE COUNT_PARTS__genmod
