        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:10 2017
        MODULE COUNT_CLOUDS__genmod
          INTERFACE 
            SUBROUTINE COUNT_CLOUDS(ILEVEL,ACTION)
              INTEGER(KIND=4) :: ILEVEL
              CHARACTER(LEN=15) :: ACTION
            END SUBROUTINE COUNT_CLOUDS
          END INTERFACE 
        END MODULE COUNT_CLOUDS__genmod
