        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:53 2017
        MODULE COURANT_FINE__genmod
          INTERFACE 
            SUBROUTINE COURANT_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE COURANT_FINE
          END INTERFACE 
        END MODULE COURANT_FINE__genmod
