        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:04 2017
        MODULE CRDIFFFINE1__genmod
          INTERFACE 
            SUBROUTINE CRDIFFFINE1(IND_GRID,NCACHE,ILEVEL,COMPUTE,IGROUP&
     &)
              INTEGER(KIND=4) :: IND_GRID(1:)
              INTEGER(KIND=4) :: NCACHE
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: COMPUTE
              INTEGER(KIND=4) :: IGROUP
            END SUBROUTINE CRDIFFFINE1
          END INTERFACE 
        END MODULE CRDIFFFINE1__genmod
