        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:04 2017
        MODULE CRDIFF_FINE__genmod
          INTERFACE 
            SUBROUTINE CRDIFF_FINE(ILEVEL,COMPUTE)
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: COMPUTE
            END SUBROUTINE CRDIFF_FINE
          END INTERFACE 
        END MODULE CRDIFF_FINE__genmod
