        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:10 2017
        MODULE CREATE_SINK__genmod
          INTERFACE 
            SUBROUTINE CREATE_SINK
            END SUBROUTINE CREATE_SINK
          END INTERFACE 
        END MODULE CREATE_SINK__genmod
