        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:09 2017
        MODULE CREATE_CLOUD_FROM_SINK__genmod
          INTERFACE 
            SUBROUTINE CREATE_CLOUD_FROM_SINK
            END SUBROUTINE CREATE_CLOUD_FROM_SINK
          END INTERFACE 
        END MODULE CREATE_CLOUD_FROM_SINK__genmod
