        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:00 2017
        MODULE CREATE_GROUPS__genmod
          INTERFACE 
            SUBROUTINE CREATE_GROUPS
            END SUBROUTINE CREATE_GROUPS
          END INTERFACE 
        END MODULE CREATE_GROUPS__genmod
