        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:49 2017
        MODULE DEFRAG__genmod
          INTERFACE 
            SUBROUTINE DEFRAG
            END SUBROUTINE DEFRAG
          END INTERFACE 
        END MODULE DEFRAG__genmod
