        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:15 2017
        MODULE DELETE_STELLAR__genmod
          INTERFACE 
            SUBROUTINE DELETE_STELLAR(FLAG_DELETE)
              USE FEEDBACK_MODULE
              LOGICAL(KIND=4), INTENT(IN) :: FLAG_DELETE(1:NSTELLAR)
            END SUBROUTINE DELETE_STELLAR
          END INTERFACE 
        END MODULE DELETE_STELLAR__genmod
