        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:00 2017
        MODULE DERIV_ARTHETA4__genmod
          INTERFACE 
            FUNCTION DERIV_ARTHETA4(TRAY,IGRP)
              REAL(KIND=8), INTENT(IN) :: TRAY
              INTEGER(KIND=4), INTENT(IN) :: IGRP
              REAL(KIND=8) :: DERIV_ARTHETA4
            END FUNCTION DERIV_ARTHETA4
          END INTERFACE 
        END MODULE DERIV_ARTHETA4__genmod
