        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:00 2017
        MODULE DERIV_RADIATION_SOURCE__genmod
          INTERFACE 
            FUNCTION DERIV_RADIATION_SOURCE(T,IGRP)
              REAL(KIND=8), INTENT(IN) :: T
              INTEGER(KIND=4), INTENT(IN) :: IGRP
              REAL(KIND=8) :: DERIV_RADIATION_SOURCE
            END FUNCTION DERIV_RADIATION_SOURCE
          END INTERFACE 
        END MODULE DERIV_RADIATION_SOURCE__genmod
