        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:54 2017
        MODULE DIFFINE1__genmod
          INTERFACE 
            SUBROUTINE DIFFINE1(IND_GRID,NCACHE,DTDIFF,ILEVEL)
              INTEGER(KIND=4) :: NCACHE
              INTEGER(KIND=4) :: IND_GRID(1:NCACHE)
              REAL(KIND=8) :: DTDIFF
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE DIFFINE1
          END INTERFACE 
        END MODULE DIFFINE1__genmod
