        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:54 2017
        MODULE DIFFUSION__genmod
          INTERFACE 
            SUBROUTINE DIFFUSION
            END SUBROUTINE DIFFUSION
          END INTERFACE 
        END MODULE DIFFUSION__genmod
