        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:54 2017
        MODULE DIFFUSION_FINE__genmod
          INTERFACE 
            SUBROUTINE DIFFUSION_FINE(ILEVEL,DTDIFF)
              INTEGER(KIND=4) :: ILEVEL
              REAL(KIND=8) :: DTDIFF
            END SUBROUTINE DIFFUSION_FINE
          END INTERFACE 
        END MODULE DIFFUSION_FINE__genmod
