        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:00 2017
        MODULE DIV_BPLANCK__genmod
          INTERFACE 
            FUNCTION DIV_BPLANCK(NU,T)
              REAL(KIND=8), INTENT(IN) :: NU
              REAL(KIND=8), INTENT(IN) :: T
              REAL(KIND=8) :: DIV_BPLANCK
            END FUNCTION DIV_BPLANCK
          END INTERFACE 
        END MODULE DIV_BPLANCK__genmod
