        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:07 2017
        MODULE EMPTY_COMM__genmod
          INTERFACE 
            SUBROUTINE EMPTY_COMM(IND_COM,NP,ILEVEL,ICPU)
              INTEGER(KIND=4) :: IND_COM(1:)
              INTEGER(KIND=4) :: NP
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: ICPU
            END SUBROUTINE EMPTY_COMM
          END INTERFACE 
        END MODULE EMPTY_COMM__genmod
