        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:50 2017
        MODULE ENERINT_EOS__genmod
          INTERFACE 
            SUBROUTINE ENERINT_EOS(RHO_TEMP,TEMP_TEMP,EEOS)
              REAL(KIND=8), INTENT(IN) :: RHO_TEMP
              REAL(KIND=8), INTENT(IN) :: TEMP_TEMP
              REAL(KIND=8), INTENT(OUT) :: EEOS
            END SUBROUTINE ENERINT_EOS
          END INTERFACE 
        END MODULE ENERINT_EOS__genmod
