        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE ENSURE_REF_RULES__genmod
          INTERFACE 
            SUBROUTINE ENSURE_REF_RULES(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE ENSURE_REF_RULES
          END INTERFACE 
        END MODULE ENSURE_REF_RULES__genmod
