        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:09 2017
        MODULE F_SINK_SINK__genmod
          INTERFACE 
            SUBROUTINE F_SINK_SINK
            END SUBROUTINE F_SINK_SINK
          END INTERFACE 
        END MODULE F_SINK_SINK__genmod
