        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:52 2017
        MODULE FILE_DESCRIPTOR_HYDRO__genmod
          INTERFACE 
            SUBROUTINE FILE_DESCRIPTOR_HYDRO(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE FILE_DESCRIPTOR_HYDRO
          END INTERFACE 
        END MODULE FILE_DESCRIPTOR_HYDRO__genmod
