        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:58 2017
        MODULE FIND_SPEED_ALFVEN__genmod
          INTERFACE 
            SUBROUTINE FIND_SPEED_ALFVEN(QVAR,VEL_INFO)
              REAL(KIND=8) :: QVAR(1:)
              REAL(KIND=8) :: VEL_INFO
            END SUBROUTINE FIND_SPEED_ALFVEN
          END INTERFACE 
        END MODULE FIND_SPEED_ALFVEN__genmod
