        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE FLAG_COARSE__genmod
          INTERFACE 
            SUBROUTINE FLAG_COARSE
            END SUBROUTINE FLAG_COARSE
          END INTERFACE 
        END MODULE FLAG_COARSE__genmod
