        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE FLAG_FORMATION_SITES__genmod
          INTERFACE 
            SUBROUTINE FLAG_FORMATION_SITES
              USE CLFIND_COMMONS
            END SUBROUTINE FLAG_FORMATION_SITES
          END INTERFACE 
        END MODULE FLAG_FORMATION_SITES__genmod
