        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:12 2017
        MODULE FLAG_PEAKS__genmod
          INTERFACE 
            SUBROUTINE FLAG_PEAKS(XX,IPEAK)
              USE AMR_COMMONS
              REAL(KIND=8) :: XX(1:NCOARSE+NGRIDMAX*8)
              INTEGER(KIND=4) :: IPEAK
            END SUBROUTINE FLAG_PEAKS
          END INTERFACE 
        END MODULE FLAG_PEAKS__genmod
