        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE FLAG_FINE__genmod
          INTERFACE 
            SUBROUTINE FLAG_FINE(ILEVEL,ICOUNT)
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: ICOUNT
            END SUBROUTINE FLAG_FINE
          END INTERFACE 
        END MODULE FLAG_FINE__genmod
