        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE FLAG__genmod
          INTERFACE 
            SUBROUTINE FLAG
            END SUBROUTINE FLAG
          END INTERFACE 
        END MODULE FLAG__genmod
