        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:17 2017
        MODULE FULL_MULTIGRID__genmod
          INTERFACE 
            SUBROUTINE FULL_MULTIGRID(ICOUNT)
              INTEGER(KIND=4) :: ICOUNT
            END SUBROUTINE FULL_MULTIGRID
          END INTERFACE 
        END MODULE FULL_MULTIGRID__genmod
