        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:17 2017
        MODULE GAUSS_SEIDEL__genmod
          INTERFACE 
            SUBROUTINE GAUSS_SEIDEL(ILEVEL,REDSTEP)
              INTEGER(KIND=4) :: ILEVEL
              LOGICAL(KIND=4) :: REDSTEP
            END SUBROUTINE GAUSS_SEIDEL
          END INTERFACE 
        END MODULE GAUSS_SEIDEL__genmod
