        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:48 2017
        MODULE GET3CUBEFATHER__genmod
          INTERFACE 
            SUBROUTINE GET3CUBEFATHER(IND_CELL_FATHER,NBORS_FATHER_CELLS&
     &,NBORS_FATHER_GRIDS,NCELL,ILEVEL)
              INTEGER(KIND=4) :: IND_CELL_FATHER(1:)
              INTEGER(KIND=4) :: NBORS_FATHER_CELLS(1:,1:)
              INTEGER(KIND=4) :: NBORS_FATHER_GRIDS(1:,1:)
              INTEGER(KIND=4) :: NCELL
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE GET3CUBEFATHER
          END INTERFACE 
        END MODULE GET3CUBEFATHER__genmod
