        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:48 2017
        MODULE GET3CUBEPOS__genmod
          INTERFACE 
            SUBROUTINE GET3CUBEPOS(IND_GRID,IND,NBORS_FATHER_CELLS,     &
     &NBORS_FATHER_GRIDS,NG)
              INTEGER(KIND=4) :: IND_GRID(1:)
              INTEGER(KIND=4) :: IND
              INTEGER(KIND=4) :: NBORS_FATHER_CELLS(1:,1:)
              INTEGER(KIND=4) :: NBORS_FATHER_GRIDS(1:,1:)
              INTEGER(KIND=4) :: NG
            END SUBROUTINE GET3CUBEPOS
          END INTERFACE 
        END MODULE GET3CUBEPOS__genmod
