        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:09 2017
        MODULE GET_CELL_CENTER__genmod
          INTERFACE 
            SUBROUTINE GET_CELL_CENTER(XX,INDEX,ILEVEL)
              REAL(KIND=8) :: XX(1:)
              INTEGER(KIND=4) :: INDEX
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE GET_CELL_CENTER
          END INTERFACE 
        END MODULE GET_CELL_CENTER__genmod
