        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE GET_LOCAL_PEAK_CPU__genmod
          INTERFACE 
            SUBROUTINE GET_LOCAL_PEAK_CPU(LOCAL_PEAK_ID,PEAK_CPU)
              INTEGER(KIND=4) :: LOCAL_PEAK_ID
              INTEGER(KIND=4) :: PEAK_CPU
            END SUBROUTINE GET_LOCAL_PEAK_CPU
          END INTERFACE 
        END MODULE GET_LOCAL_PEAK_CPU__genmod
