        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:12 2017
        MODULE GET_CELL_INDEX_FAST__genmod
          INTERFACE 
            SUBROUTINE GET_CELL_INDEX_FAST(INDP,CELL_LEV,XPART,IND_GRID,&
     &NBORS_FATHER_CELLS,NP,ILEVEL)
              INTEGER(KIND=4) :: INDP(1:)
              INTEGER(KIND=4) :: CELL_LEV(1:)
              REAL(KIND=8) :: XPART(1:,1:)
              INTEGER(KIND=4) :: IND_GRID
              INTEGER(KIND=4) :: NBORS_FATHER_CELLS(1:)
              INTEGER(KIND=4) :: NP
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE GET_CELL_INDEX_FAST
          END INTERFACE 
        END MODULE GET_CELL_INDEX_FAST__genmod
