        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE GET_LOCAL_PEAK_ID__genmod
          INTERFACE 
            SUBROUTINE GET_LOCAL_PEAK_ID(GLOBAL_PEAK_ID,LOCAL_PEAK_ID)
              INTEGER(KIND=4) :: GLOBAL_PEAK_ID
              INTEGER(KIND=4) :: LOCAL_PEAK_ID
            END SUBROUTINE GET_LOCAL_PEAK_ID
          END INTERFACE 
        END MODULE GET_LOCAL_PEAK_ID__genmod
