        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:01 2017
        MODULE GET_CELL_INDEX2__genmod
          INTERFACE 
            SUBROUTINE GET_CELL_INDEX2(CELL_INDEX2,CELL_LEVL2,XPART2,   &
     &ILEVEL)
              INTEGER(KIND=4) :: CELL_INDEX2
              INTEGER(KIND=4) :: CELL_LEVL2
              REAL(KIND=8) :: XPART2(1:)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE GET_CELL_INDEX2
          END INTERFACE 
        END MODULE GET_CELL_INDEX2__genmod
