        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:21 2017
        MODULE GET_RT_COURANT_COARSE__genmod
          INTERFACE 
            SUBROUTINE GET_RT_COURANT_COARSE(DT)
              REAL(KIND=8) :: DT
            END SUBROUTINE GET_RT_COURANT_COARSE
          END INTERFACE 
        END MODULE GET_RT_COURANT_COARSE__genmod
