        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:45 2017
        MODULE GETAGEGYR__genmod
          INTERFACE 
            SUBROUTINE GETAGEGYR(T_BIRTH_PROPER,AGE)
              REAL(KIND=8) :: T_BIRTH_PROPER
              REAL(KIND=8) :: AGE
            END SUBROUTINE GETAGEGYR
          END INTERFACE 
        END MODULE GETAGEGYR__genmod
