        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:45 2017
        MODULE GETAGESEC__genmod
          INTERFACE 
            SUBROUTINE GETAGESEC(T_BIRTH_PROPER,AGE)
              REAL(KIND=8) :: T_BIRTH_PROPER
              REAL(KIND=8) :: AGE
            END SUBROUTINE GETAGESEC
          END INTERFACE 
        END MODULE GETAGESEC__genmod
