        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:48 2017
        MODULE GETINDICES3CUBE__genmod
          INTERFACE 
            SUBROUTINE GETINDICES3CUBE(LLL,MMM)
              INTEGER(KIND=4) :: LLL(1:,1:,1:)
              INTEGER(KIND=4) :: MMM(1:,1:,1:)
            END SUBROUTINE GETINDICES3CUBE
          END INTERFACE 
        END MODULE GETINDICES3CUBE__genmod
