        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:48 2017
        MODULE GETNBORGRIDS__genmod
          INTERFACE 
            SUBROUTINE GETNBORGRIDS(IGRID,IGRIDN,NGRID)
              INTEGER(KIND=4) :: IGRID(1:)
              INTEGER(KIND=4) :: IGRIDN(1:,0:)
              INTEGER(KIND=4) :: NGRID
            END SUBROUTINE GETNBORGRIDS
          END INTERFACE 
        END MODULE GETNBORGRIDS__genmod
