        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:48 2017
        MODULE GETNBORFATHER__genmod
          INTERFACE 
            SUBROUTINE GETNBORFATHER(IND_CELL,IND_FATHER,NCELL,ILEVEL)
              INTEGER(KIND=4) :: IND_CELL(1:)
              INTEGER(KIND=4) :: IND_FATHER(1:,0:)
              INTEGER(KIND=4) :: NCELL
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE GETNBORFATHER
          END INTERFACE 
        END MODULE GETNBORFATHER__genmod
