        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:08 2017
        MODULE GETNBOR__genmod
          INTERFACE 
            SUBROUTINE GETNBOR(IND_CELL,IND_FATHER,NCELL,ILEVEL)
              INTEGER(KIND=4) :: IND_CELL(1:)
              INTEGER(KIND=4) :: IND_FATHER(1:,0:)
              INTEGER(KIND=4) :: NCELL
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE GETNBOR
          END INTERFACE 
        END MODULE GETNBOR__genmod
