        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:48 2017
        MODULE GETNBORCELLS__genmod
          INTERFACE 
            SUBROUTINE GETNBORCELLS(IGRIDN,IND,ICELLN,NG)
              INTEGER(KIND=4) :: IGRIDN(1:,0:)
              INTEGER(KIND=4) :: IND
              INTEGER(KIND=4) :: ICELLN(1:,1:)
              INTEGER(KIND=4) :: NG
            END SUBROUTINE GETNBORCELLS
          END INTERFACE 
        END MODULE GETNBORCELLS__genmod
