        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:45 2017
        MODULE GETPROPERTIME__genmod
          INTERFACE 
            SUBROUTINE GETPROPERTIME(TAU,TPROPER)
              REAL(KIND=8) :: TAU
              REAL(KIND=8) :: TPROPER
            END SUBROUTINE GETPROPERTIME
          END INTERFACE 
        END MODULE GETPROPERTIME__genmod
