        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:53 2017
        MODULE GODFINE1__genmod
          INTERFACE 
            SUBROUTINE GODFINE1(IND_GRID,NCACHE,ILEVEL)
              INTEGER(KIND=4) :: IND_GRID(1:)
              INTEGER(KIND=4) :: NCACHE
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE GODFINE1
          END INTERFACE 
        END MODULE GODFINE1__genmod
