        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:16 2017
        MODULE GRADIENT_PHI__genmod
          INTERFACE 
            SUBROUTINE GRADIENT_PHI(IND_GRID,NGRID,ILEVEL,ICOUNT)
              INTEGER(KIND=4) :: IND_GRID(1:)
              INTEGER(KIND=4) :: NGRID
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: ICOUNT
            END SUBROUTINE GRADIENT_PHI
          END INTERFACE 
        END MODULE GRADIENT_PHI__genmod
