        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:10 2017
        MODULE GROW_SINK__genmod
          INTERFACE 
            SUBROUTINE GROW_SINK(ILEVEL,ON_CREATION)
              INTEGER(KIND=4) :: ILEVEL
              LOGICAL(KIND=4) :: ON_CREATION
            END SUBROUTINE GROW_SINK
          END INTERFACE 
        END MODULE GROW_SINK__genmod
