        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:59 2017
        MODULE HYDRO_FLAG__genmod
          INTERFACE 
            SUBROUTINE HYDRO_FLAG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE HYDRO_FLAG
          END INTERFACE 
        END MODULE HYDRO_FLAG__genmod
