        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:58 2017
        MODULE HYDRO_ACOUSTIC__genmod
          INTERFACE 
            SUBROUTINE HYDRO_ACOUSTIC(QLEFT,QRIGHT,FGDNV)
              REAL(KIND=8) :: QLEFT(1:)
              REAL(KIND=8) :: QRIGHT(1:)
              REAL(KIND=8) :: FGDNV(1:)
            END SUBROUTINE HYDRO_ACOUSTIC
          END INTERFACE 
        END MODULE HYDRO_ACOUSTIC__genmod
