        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE INIT_REFMAP__genmod
          INTERFACE 
            SUBROUTINE INIT_REFMAP
            END SUBROUTINE INIT_REFMAP
          END INTERFACE 
        END MODULE INIT_REFMAP__genmod
