        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:52 2017
        MODULE INIT_FLOW__genmod
          INTERFACE 
            SUBROUTINE INIT_FLOW
            END SUBROUTINE INIT_FLOW
          END INTERFACE 
        END MODULE INIT_FLOW__genmod
