        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:45 2017
        MODULE INIT_TIME__genmod
          INTERFACE 
            SUBROUTINE INIT_TIME
            END SUBROUTINE INIT_TIME
          END INTERFACE 
        END MODULE INIT_TIME__genmod
