        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:45 2017
        MODULE INIT_COSMO__genmod
          INTERFACE 
            SUBROUTINE INIT_COSMO
            END SUBROUTINE INIT_COSMO
          END INTERFACE 
        END MODULE INIT_COSMO__genmod
