        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:14 2017
        MODULE INIT_SINK__genmod
          INTERFACE 
            SUBROUTINE INIT_SINK
            END SUBROUTINE INIT_SINK
          END INTERFACE 
        END MODULE INIT_SINK__genmod
