        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE INIT_FLAG__genmod
          INTERFACE 
            SUBROUTINE INIT_FLAG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE INIT_FLAG
          END INTERFACE 
        END MODULE INIT_FLAG__genmod
