        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE INIT_REFMAP_FINE__genmod
          INTERFACE 
            SUBROUTINE INIT_REFMAP_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE INIT_REFMAP_FINE
          END INTERFACE 
        END MODULE INIT_REFMAP_FINE__genmod
