        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:45 2017
        MODULE INIT_REFINE_2__genmod
          INTERFACE 
            SUBROUTINE INIT_REFINE_2
            END SUBROUTINE INIT_REFINE_2
          END INTERFACE 
        END MODULE INIT_REFINE_2__genmod
