        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:52 2017
        MODULE INIT_FLOW_FINE__genmod
          INTERFACE 
            SUBROUTINE INIT_FLOW_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE INIT_FLOW_FINE
          END INTERFACE 
        END MODULE INIT_FLOW_FINE__genmod
