        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:16 2017
        MODULE INIT_POISSON__genmod
          INTERFACE 
            SUBROUTINE INIT_POISSON
            END SUBROUTINE INIT_POISSON
          END INTERFACE 
        END MODULE INIT_POISSON__genmod
