        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:45 2017
        MODULE INIT_REFINE__genmod
          INTERFACE 
            SUBROUTINE INIT_REFINE
            END SUBROUTINE INIT_REFINE
          END INTERFACE 
        END MODULE INIT_REFINE__genmod
