        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:15 2017
        MODULE INIT_STELLAR__genmod
          INTERFACE 
            SUBROUTINE INIT_STELLAR
            END SUBROUTINE INIT_STELLAR
          END INTERFACE 
        END MODULE INIT_STELLAR__genmod
