        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:47 2017
        MODULE INIT_BOUNDARY_FINE__genmod
          INTERFACE 
            SUBROUTINE INIT_BOUNDARY_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE INIT_BOUNDARY_FINE
          END INTERFACE 
        END MODULE INIT_BOUNDARY_FINE__genmod
