        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:04 2017
        MODULE INIT_PART__genmod
          INTERFACE 
            SUBROUTINE INIT_PART
              USE AMR_COMMONS
            END SUBROUTINE INIT_PART
          END INTERFACE 
        END MODULE INIT_PART__genmod
