        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:44 2017
        MODULE INIT_FILE__genmod
          INTERFACE 
            SUBROUTINE INIT_FILE
            END SUBROUTINE INIT_FILE
          END INTERFACE 
        END MODULE INIT_FILE__genmod
