        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:47 2017
        MODULE INIT_BOUNDARY_COARSE__genmod
          INTERFACE 
            SUBROUTINE INIT_BOUNDARY_COARSE
            END SUBROUTINE INIT_BOUNDARY_COARSE
          END INTERFACE 
        END MODULE INIT_BOUNDARY_COARSE__genmod
