        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:52 2017
        MODULE INIT_HYDRO__genmod
          INTERFACE 
            SUBROUTINE INIT_HYDRO
            END SUBROUTINE INIT_HYDRO
          END INTERFACE 
        END MODULE INIT_HYDRO__genmod
