        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:01 2017
        MODULE INIT_RADIATIVE__genmod
          INTERFACE 
            SUBROUTINE INIT_RADIATIVE
            END SUBROUTINE INIT_RADIATIVE
          END INTERFACE 
        END MODULE INIT_RADIATIVE__genmod
