        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:03 2017
        MODULE INTERPOL_HYDRO_COND__genmod
          INTERFACE 
            SUBROUTINE INTERPOL_HYDRO_COND(U1,IND1,U2,NN)
              REAL(KIND=8) :: U1(1:,0:,1:)
              INTEGER(KIND=4) :: IND1(1:,0:)
              REAL(KIND=8) :: U2(1:,1:,1:)
              INTEGER(KIND=4) :: NN
            END SUBROUTINE INTERPOL_HYDRO_COND
          END INTERFACE 
        END MODULE INTERPOL_HYDRO_COND__genmod
