        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:18 2017
        MODULE INTERPOLATE_AND_CORRECT_COARSE__genmod
          INTERFACE 
            SUBROUTINE INTERPOLATE_AND_CORRECT_COARSE(IFINELEVEL)
              INTEGER(KIND=4), INTENT(IN) :: IFINELEVEL
            END SUBROUTINE INTERPOLATE_AND_CORRECT_COARSE
          END INTERFACE 
        END MODULE INTERPOLATE_AND_CORRECT_COARSE__genmod
