        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:59 2017
        MODULE JEANS_LENGTH_REFINE__genmod
          INTERFACE 
            SUBROUTINE JEANS_LENGTH_REFINE(IND_CELL,OK,NCELL,ILEVEL)
              INTEGER(KIND=4) :: IND_CELL(1:)
              LOGICAL(KIND=4) :: OK(1:)
              INTEGER(KIND=4) :: NCELL
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE JEANS_LENGTH_REFINE
          END INTERFACE 
        END MODULE JEANS_LENGTH_REFINE__genmod
