        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:09 2017
        MODULE KILL_ENTIRE_CLOUD__genmod
          INTERFACE 
            SUBROUTINE KILL_ENTIRE_CLOUD(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE KILL_ENTIRE_CLOUD
          END INTERFACE 
        END MODULE KILL_ENTIRE_CLOUD__genmod
