        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:07 2017
        MODULE KILL_TREE_FINE__genmod
          INTERFACE 
            SUBROUTINE KILL_TREE_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE KILL_TREE_FINE
          END INTERFACE 
        END MODULE KILL_TREE_FINE__genmod
