        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:48 2017
        MODULE KILL_GRID__genmod
          INTERFACE 
            SUBROUTINE KILL_GRID(IND_CELL,ILEVEL,NN,IBOUND,             &
     &BOUNDARY_REGION)
              INTEGER(KIND=4) :: IND_CELL(1:)
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: NN
              INTEGER(KIND=4) :: IBOUND
              LOGICAL(KIND=4) :: BOUNDARY_REGION
            END SUBROUTINE KILL_GRID
          END INTERFACE 
        END MODULE KILL_GRID__genmod
