        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:11 2017
        MODULE KINETIC_FEEDBACK__genmod
          INTERFACE 
            SUBROUTINE KINETIC_FEEDBACK
              USE AMR_COMMONS
            END SUBROUTINE KINETIC_FEEDBACK
          END INTERFACE 
        END MODULE KINETIC_FEEDBACK__genmod
