        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:04 2017
        MODULE LOAD_GADGET__genmod
          INTERFACE 
            SUBROUTINE LOAD_GADGET
              USE AMR_COMMONS
            END SUBROUTINE LOAD_GADGET
          END INTERFACE 
        END MODULE LOAD_GADGET__genmod
