        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:49 2017
        MODULE LOAD_BALANCE__genmod
          INTERFACE 
            SUBROUTINE LOAD_BALANCE
              USE BISECTION
            END SUBROUTINE LOAD_BALANCE
          END INTERFACE 
        END MODULE LOAD_BALANCE__genmod
