        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:47 2017
        MODULE MAKE_VIRTUAL_COARSE_INT__genmod
          INTERFACE 
            SUBROUTINE MAKE_VIRTUAL_COARSE_INT(XX)
              USE AMR_COMMONS
              INTEGER(KIND=4) :: XX(1:NCOARSE+NGRIDMAX*8)
            END SUBROUTINE MAKE_VIRTUAL_COARSE_INT
          END INTERFACE 
        END MODULE MAKE_VIRTUAL_COARSE_INT__genmod
