        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:17 2017
        MODULE MAKE_VIRTUAL_MG_DP__genmod
          INTERFACE 
            SUBROUTINE MAKE_VIRTUAL_MG_DP(IVAR,ILEVEL)
              USE AMR_COMMONS
              INTEGER(KIND=4) :: IVAR
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MAKE_VIRTUAL_MG_DP
          END INTERFACE 
        END MODULE MAKE_VIRTUAL_MG_DP__genmod
