        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:15 2017
        MODULE MAKE_STELLAR_FROM_SINKS__genmod
          INTERFACE 
            SUBROUTINE MAKE_STELLAR_FROM_SINKS
              USE FEEDBACK_MODULE
            END SUBROUTINE MAKE_STELLAR_FROM_SINKS
          END INTERFACE 
        END MODULE MAKE_STELLAR_FROM_SINKS__genmod
