        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:48 2017
        MODULE MAKE_GRID_FINE__genmod
          INTERFACE 
            SUBROUTINE MAKE_GRID_FINE(IND_GRID,IND_CELL,IND,ILEVEL,NN,  &
     &IBOUND,BOUNDARY_REGION)
              INTEGER(KIND=4) :: IND_GRID(1:)
              INTEGER(KIND=4) :: IND_CELL(1:)
              INTEGER(KIND=4) :: IND
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: NN
              INTEGER(KIND=4) :: IBOUND
              LOGICAL(KIND=4) :: BOUNDARY_REGION
            END SUBROUTINE MAKE_GRID_FINE
          END INTERFACE 
        END MODULE MAKE_GRID_FINE__genmod
