        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:01 2017
        MODULE MAKE_BOUNDARY_DIFFUSION__genmod
          INTERFACE 
            SUBROUTINE MAKE_BOUNDARY_DIFFUSION(ILEVEL,IGROUP)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
              INTEGER(KIND=4), INTENT(IN) :: IGROUP
            END SUBROUTINE MAKE_BOUNDARY_DIFFUSION
          END INTERFACE 
        END MODULE MAKE_BOUNDARY_DIFFUSION__genmod
