        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:47 2017
        MODULE MAKE_BOUNDARY_FLAG__genmod
          INTERFACE 
            SUBROUTINE MAKE_BOUNDARY_FLAG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MAKE_BOUNDARY_FLAG
          END INTERFACE 
        END MODULE MAKE_BOUNDARY_FLAG__genmod
