        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:47 2017
        MODULE MAKE_BOUNDARY_COARSE__genmod
          INTERFACE 
            SUBROUTINE MAKE_BOUNDARY_COARSE
            END SUBROUTINE MAKE_BOUNDARY_COARSE
          END INTERFACE 
        END MODULE MAKE_BOUNDARY_COARSE__genmod
