        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:19 2017
        MODULE MAKE_BOUNDARY_MASK__genmod
          INTERFACE 
            SUBROUTINE MAKE_BOUNDARY_MASK(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MAKE_BOUNDARY_MASK
          END INTERFACE 
        END MODULE MAKE_BOUNDARY_MASK__genmod
