        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:17 2017
        MODULE MAKE_FINE_MASK__genmod
          INTERFACE 
            SUBROUTINE MAKE_FINE_MASK(ILEVEL)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
            END SUBROUTINE MAKE_FINE_MASK
          END INTERFACE 
        END MODULE MAKE_FINE_MASK__genmod
