        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:09 2017
        MODULE MAKE_SINK_FROM_CLUMP__genmod
          INTERFACE 
            SUBROUTINE MAKE_SINK_FROM_CLUMP(ILEVEL)
              USE AMR_COMMONS
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MAKE_SINK_FROM_CLUMP
          END INTERFACE 
        END MODULE MAKE_SINK_FROM_CLUMP__genmod
