        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:01 2017
        MODULE MAKE_BOUNDARY_DIFFUSION_TOT__genmod
          INTERFACE 
            SUBROUTINE MAKE_BOUNDARY_DIFFUSION_TOT(ILEVEL)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
            END SUBROUTINE MAKE_BOUNDARY_DIFFUSION_TOT
          END INTERFACE 
        END MODULE MAKE_BOUNDARY_DIFFUSION_TOT__genmod
