        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:16 2017
        MODULE MAKE_MULTIPOLE_PHI__genmod
          INTERFACE 
            SUBROUTINE MAKE_MULTIPOLE_PHI(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MAKE_MULTIPOLE_PHI
          END INTERFACE 
        END MODULE MAKE_MULTIPOLE_PHI__genmod
