        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:15 2017
        MODULE MAKE_STELLAR_FROM_SINKS_GLOB__genmod
          INTERFACE 
            SUBROUTINE MAKE_STELLAR_FROM_SINKS_GLOB
              USE FEEDBACK_MODULE
              USE PM_COMMONS
            END SUBROUTINE MAKE_STELLAR_FROM_SINKS_GLOB
          END INTERFACE 
        END MODULE MAKE_STELLAR_FROM_SINKS_GLOB__genmod
