        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:16 2017
        MODULE MAKE_INITIAL_PHI__genmod
          INTERFACE 
            SUBROUTINE MAKE_INITIAL_PHI(ILEVEL,ICOUNT)
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: ICOUNT
            END SUBROUTINE MAKE_INITIAL_PHI
          END INTERFACE 
        END MODULE MAKE_INITIAL_PHI__genmod
