        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:48 2017
        MODULE MAKE_GRID_COARSE__genmod
          INTERFACE 
            SUBROUTINE MAKE_GRID_COARSE(IND_CELL,IBOUND,BOUNDARY_REGION)
              INTEGER(KIND=4) :: IND_CELL
              INTEGER(KIND=4) :: IBOUND
              LOGICAL(KIND=4) :: BOUNDARY_REGION
            END SUBROUTINE MAKE_GRID_COARSE
          END INTERFACE 
        END MODULE MAKE_GRID_COARSE__genmod
