        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:02 2017
        MODULE MAKE_BOUNDARY_CRDIFFUSION__genmod
          INTERFACE 
            SUBROUTINE MAKE_BOUNDARY_CRDIFFUSION(ILEVEL,IND_CR)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
              INTEGER(KIND=4), INTENT(IN) :: IND_CR
            END SUBROUTINE MAKE_BOUNDARY_CRDIFFUSION
          END INTERFACE 
        END MODULE MAKE_BOUNDARY_CRDIFFUSION__genmod
