        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:07 2017
        MODULE MERGE_TREE_FINE__genmod
          INTERFACE 
            SUBROUTINE MERGE_TREE_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MERGE_TREE_FINE
          END INTERFACE 
        END MODULE MERGE_TREE_FINE__genmod
