        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:09 2017
        MODULE MERGE_SMBH_SINK__genmod
          INTERFACE 
            SUBROUTINE MERGE_SMBH_SINK
            END SUBROUTINE MERGE_SMBH_SINK
          END INTERFACE 
        END MODULE MERGE_SMBH_SINK__genmod
