        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE MERGE_CLUMPS__genmod
          INTERFACE 
            SUBROUTINE MERGE_CLUMPS(ACTION)
              USE CLFIND_COMMONS
              CHARACTER(LEN=9) :: ACTION
            END SUBROUTINE MERGE_CLUMPS
          END INTERFACE 
        END MODULE MERGE_CLUMPS__genmod
