        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:09 2017
        MODULE MERGE_STAR_SINK__genmod
          INTERFACE 
            SUBROUTINE MERGE_STAR_SINK
            END SUBROUTINE MERGE_STAR_SINK
          END INTERFACE 
        END MODULE MERGE_STAR_SINK__genmod
