        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:07 2017
        MODULE MOVE_FINE__genmod
          INTERFACE 
            SUBROUTINE MOVE_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MOVE_FINE
          END INTERFACE 
        END MODULE MOVE_FINE__genmod
