        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:05 2017
        MODULE MULTIPOLE_FINE__genmod
          INTERFACE 
            SUBROUTINE MULTIPOLE_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MULTIPOLE_FINE
          END INTERFACE 
        END MODULE MULTIPOLE_FINE__genmod
