        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:17 2017
        MODULE MULTIGRID_FINE__genmod
          INTERFACE 
            SUBROUTINE MULTIGRID_FINE(ILEVEL,ICOUNT)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
              INTEGER(KIND=4), INTENT(IN) :: ICOUNT
            END SUBROUTINE MULTIGRID_FINE
          END INTERFACE 
        END MODULE MULTIGRID_FINE__genmod
