        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:17 2017
        MODULE MULTIGRID_COARSE__genmod
          INTERFACE 
            SUBROUTINE MULTIGRID_COARSE(ILEVEL,ICOUNT)
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: ICOUNT
            END SUBROUTINE MULTIGRID_COARSE
          END INTERFACE 
        END MODULE MULTIGRID_COARSE__genmod
