        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:17 2017
        MODULE MULTIGRID_ITERATOR__genmod
          INTERFACE 
            RECURSIVE SUBROUTINE MULTIGRID_ITERATOR(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MULTIGRID_ITERATOR
          END INTERFACE 
        END MODULE MULTIGRID_ITERATOR__genmod
