        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:07 2017
        MODULE NEWDT_FINE__genmod
          INTERFACE 
            SUBROUTINE NEWDT_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE NEWDT_FINE
          END INTERFACE 
        END MODULE NEWDT_FINE__genmod
