        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:51 2017
        MODULE OUTPUT_FRAME__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_FRAME
            END SUBROUTINE OUTPUT_FRAME
          END INTERFACE 
        END MODULE OUTPUT_FRAME__genmod
