        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:15 2017
        MODULE OUTPUT_SINK_PROPERTIES__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_SINK_PROPERTIES(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_SINK_PROPERTIES
          END INTERFACE 
        END MODULE OUTPUT_SINK_PROPERTIES__genmod
