        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:20 2017
        MODULE OUTPUT_RTINFO__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_RTINFO(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_RTINFO
          END INTERFACE 
        END MODULE OUTPUT_RTINFO__genmod
