        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:15 2017
        MODULE OUTPUT_CLUMP_PROPERTIES__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_CLUMP_PROPERTIES(FILELOC)
              USE CLFIND_COMMONS
              CHARACTER(LEN=80) :: FILELOC
            END SUBROUTINE OUTPUT_CLUMP_PROPERTIES
          END INTERFACE 
        END MODULE OUTPUT_CLUMP_PROPERTIES__genmod
