        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:20 2017
        MODULE OUTPUT_RT_STATS__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_RT_STATS
            END SUBROUTINE OUTPUT_RT_STATS
          END INTERFACE 
        END MODULE OUTPUT_RT_STATS__genmod
