        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:44 2017
        MODULE OUTPUT_PATCH__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_PATCH(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_PATCH
          END INTERFACE 
        END MODULE OUTPUT_PATCH__genmod
