        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:15 2017
        MODULE OUTPUT_STELLAR_CSV__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_STELLAR_CSV(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_STELLAR_CSV
          END INTERFACE 
        END MODULE OUTPUT_STELLAR_CSV__genmod
