        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:45 2017
        MODULE OUTPUT_TIMER__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_TIMER(WRITE_FILE,FILENAME)
              USE AMR_COMMONS
              LOGICAL(KIND=4) :: WRITE_FILE
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_TIMER
          END INTERFACE 
        END MODULE OUTPUT_TIMER__genmod
