        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:14 2017
        MODULE OUTPUT_SINK_CSV__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_SINK_CSV(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_SINK_CSV
          END INTERFACE 
        END MODULE OUTPUT_SINK_CSV__genmod
