        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE OUTPUT_INFO__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_INFO(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_INFO
          END INTERFACE 
        END MODULE OUTPUT_INFO__genmod
