        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:43 2017
        MODULE OUTPUT_MAKEFILE__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_MAKEFILE(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_MAKEFILE
          END INTERFACE 
        END MODULE OUTPUT_MAKEFILE__genmod
