        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:50 2017
        MODULE OUTPUT_CONE__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_CONE
            END SUBROUTINE OUTPUT_CONE
          END INTERFACE 
        END MODULE OUTPUT_CONE__genmod
