        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE OUTPUT_HEADER__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_HEADER(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_HEADER
          END INTERFACE 
        END MODULE OUTPUT_HEADER__genmod
