        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:14 2017
        MODULE OUTPUT_SINK__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_SINK(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_SINK
          END INTERFACE 
        END MODULE OUTPUT_SINK__genmod
