        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:22 2017
        MODULE OUTPUT_SIGNAL__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_SIGNAL
            END SUBROUTINE OUTPUT_SIGNAL
          END INTERFACE 
        END MODULE OUTPUT_SIGNAL__genmod
