        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE POISSON_REFINE__genmod
          INTERFACE 
            SUBROUTINE POISSON_REFINE(IND_CELL,OK,NCELL,ILEVEL)
              INTEGER(KIND=4) :: IND_CELL(1:)
              LOGICAL(KIND=4) :: OK(1:)
              INTEGER(KIND=4) :: NCELL
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE POISSON_REFINE
          END INTERFACE 
        END MODULE POISSON_REFINE__genmod
