        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:50 2017
        MODULE PRESSURE_EOS__genmod
          INTERFACE 
            SUBROUTINE PRESSURE_EOS(RHO_TEMP,ENINT_TEMP,PEOS)
              REAL(KIND=8), INTENT(IN) :: RHO_TEMP
              REAL(KIND=8), INTENT(IN) :: ENINT_TEMP
              REAL(KIND=8), INTENT(OUT) :: PEOS
            END SUBROUTINE PRESSURE_EOS
          END INTERFACE 
        END MODULE PRESSURE_EOS__genmod
