        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:09 2017
        MODULE PRINT_SINK_PROPERTIES__genmod
          INTERFACE 
            SUBROUTINE PRINT_SINK_PROPERTIES(DMEDOVERDT,RHO_INF,R2)
              USE PM_COMMONS
              REAL(KIND=8) :: DMEDOVERDT(1:NSINKMAX)
              REAL(KIND=8) :: RHO_INF
              REAL(KIND=8) :: R2
            END SUBROUTINE PRINT_SINK_PROPERTIES
          END INTERFACE 
        END MODULE PRINT_SINK_PROPERTIES__genmod
