        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:17 2017
        MODULE PROLONG__genmod
          INTERFACE 
            SUBROUTINE PROLONG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE PROLONG
          END INTERFACE 
        END MODULE PROLONG__genmod
