        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:12 2017
        MODULE PROPAGATE_FLAG__genmod
          INTERFACE 
            SUBROUTINE PROPAGATE_FLAG(NMOVE,NZERO)
              INTEGER(KIND=4) :: NMOVE
              INTEGER(KIND=4) :: NZERO
            END SUBROUTINE PROPAGATE_FLAG
          END INTERFACE 
        END MODULE PROPAGATE_FLAG__genmod
