        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:09 2017
        MODULE QUENCHING__genmod
          INTERFACE 
            SUBROUTINE QUENCHING(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE QUENCHING
          END INTERFACE 
        END MODULE QUENCHING__genmod
