        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:50 2017
        MODULE QUICK_SORT_DP__genmod
          INTERFACE 
            SUBROUTINE QUICK_SORT_DP(LIST,ORDER,N)
              INTEGER(KIND=4) :: N
              REAL(KIND=8), INTENT(INOUT) :: LIST(1:N)
              INTEGER(KIND=4), INTENT(OUT) :: ORDER(1:N)
            END SUBROUTINE QUICK_SORT_DP
          END INTERFACE 
        END MODULE QUICK_SORT_DP__genmod
