        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:53 2017
        MODULE RAD_FORCE_FINE__genmod
          INTERFACE 
            SUBROUTINE RAD_FORCE_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE RAD_FORCE_FINE
          END INTERFACE 
        END MODULE RAD_FORCE_FINE__genmod
