        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:00 2017
        MODULE RADIATION_SOURCE__genmod
          INTERFACE 
            FUNCTION RADIATION_SOURCE(T,IGRP)
              REAL(KIND=8), INTENT(IN) :: T
              INTEGER(KIND=4), INTENT(IN) :: IGRP
              REAL(KIND=8) :: RADIATION_SOURCE
            END FUNCTION RADIATION_SOURCE
          END INTERFACE 
        END MODULE RADIATION_SOURCE__genmod
