        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:10 2017
        MODULE RADIATIVE_FEEDBACK_SINK__genmod
          INTERFACE 
            SUBROUTINE RADIATIVE_FEEDBACK_SINK(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE RADIATIVE_FEEDBACK_SINK
          END INTERFACE 
        END MODULE RADIATIVE_FEEDBACK_SINK__genmod
