        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:12 2017
        MODULE READ_CLUMPFIND_PARAMS__genmod
          INTERFACE 
            SUBROUTINE READ_CLUMPFIND_PARAMS
            END SUBROUTINE READ_CLUMPFIND_PARAMS
          END INTERFACE 
        END MODULE READ_CLUMPFIND_PARAMS__genmod
