        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:59 2017
        MODULE READ_HYDRO_PARAMS__genmod
          INTERFACE 
            SUBROUTINE READ_HYDRO_PARAMS(NML_OK)
              LOGICAL(KIND=4) :: NML_OK
            END SUBROUTINE READ_HYDRO_PARAMS
          END INTERFACE 
        END MODULE READ_HYDRO_PARAMS__genmod
