        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:44 2017
        MODULE READ_PARAMS__genmod
          INTERFACE 
            SUBROUTINE READ_PARAMS
            END SUBROUTINE READ_PARAMS
          END INTERFACE 
        END MODULE READ_PARAMS__genmod
