        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:20 2017
        MODULE READ_RT_GROUPS__genmod
          INTERFACE 
            SUBROUTINE READ_RT_GROUPS
            END SUBROUTINE READ_RT_GROUPS
          END INTERFACE 
        END MODULE READ_RT_GROUPS__genmod
