        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:10 2017
        MODULE READ_SINK_PARAMS__genmod
          INTERFACE 
            SUBROUTINE READ_SINK_PARAMS
            END SUBROUTINE READ_SINK_PARAMS
          END INTERFACE 
        END MODULE READ_SINK_PARAMS__genmod
