        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:00 2017
        MODULE READ_OMEGAS__genmod
          INTERFACE 
            SUBROUTINE READ_OMEGAS
            END SUBROUTINE READ_OMEGAS
          END INTERFACE 
        END MODULE READ_OMEGAS__genmod
