        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:43 2017
        MODULE READ_CLOUD_PARAMS__genmod
          INTERFACE 
            SUBROUTINE READ_CLOUD_PARAMS(NML_OK)
              LOGICAL(KIND=4) :: NML_OK
            END SUBROUTINE READ_CLOUD_PARAMS
          END INTERFACE 
        END MODULE READ_CLOUD_PARAMS__genmod
