        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:17 2017
        MODULE RECURSIVE_MULTIGRID_COARSE__genmod
          INTERFACE 
            RECURSIVE SUBROUTINE RECURSIVE_MULTIGRID_COARSE(IFINELEVEL, &
     &SAFE)
              INTEGER(KIND=4), INTENT(IN) :: IFINELEVEL
              LOGICAL(KIND=4), INTENT(IN) :: SAFE
            END SUBROUTINE RECURSIVE_MULTIGRID_COARSE
          END INTERFACE 
        END MODULE RECURSIVE_MULTIGRID_COARSE__genmod
