        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:41 2017
        MODULE REDUCE_FLUX__genmod
          INTERFACE 
            SUBROUTINE REDUCE_FLUX(FP,CNP)
              REAL(KIND=8) :: FP(3)
              REAL(KIND=8) :: CNP
            END SUBROUTINE REDUCE_FLUX
          END INTERFACE 
        END MODULE REDUCE_FLUX__genmod
