        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:48 2017
        MODULE REFINE_COARSE__genmod
          INTERFACE 
            SUBROUTINE REFINE_COARSE
            END SUBROUTINE REFINE_COARSE
          END INTERFACE 
        END MODULE REFINE_COARSE__genmod
