        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:48 2017
        MODULE REFINE_FINE__genmod
          INTERFACE 
            SUBROUTINE REFINE_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE REFINE_FINE
          END INTERFACE 
        END MODULE REFINE_FINE__genmod
