        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:45 2017
        MODULE RESET_TIMER__genmod
          INTERFACE 
            SUBROUTINE RESET_TIMER
            END SUBROUTINE RESET_TIMER
          END INTERFACE 
        END MODULE RESET_TIMER__genmod
