        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:18 2017
        MODULE RESTRICT_MASK_FINE__genmod
          INTERFACE 
            SUBROUTINE RESTRICT_MASK_FINE(IFINELEVEL,ALLMASKED)
              INTEGER(KIND=4), INTENT(IN) :: IFINELEVEL
              LOGICAL(KIND=4), INTENT(OUT) :: ALLMASKED
            END SUBROUTINE RESTRICT_MASK_FINE
          END INTERFACE 
        END MODULE RESTRICT_MASK_FINE__genmod
