        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:17 2017
        MODULE RESTRICT__genmod
          INTERFACE 
            SUBROUTINE RESTRICT(IND_GRID,NGRID,ILEVEL,MULTIGRID)
              INTEGER(KIND=4) :: IND_GRID(1:)
              INTEGER(KIND=4) :: NGRID
              INTEGER(KIND=4) :: ILEVEL
              LOGICAL(KIND=4) :: MULTIGRID
            END SUBROUTINE RESTRICT
          END INTERFACE 
        END MODULE RESTRICT__genmod
