        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:17 2017
        MODULE RESTRICTION_FINE__genmod
          INTERFACE 
            SUBROUTINE RESTRICTION_FINE(ILEVEL,MULTIGRID)
              INTEGER(KIND=4) :: ILEVEL
              LOGICAL(KIND=4) :: MULTIGRID
            END SUBROUTINE RESTRICTION_FINE
          END INTERFACE 
        END MODULE RESTRICTION_FINE__genmod
