        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:18 2017
        MODULE RESTRICT_MASK_FINE_REVERSE__genmod
          INTERFACE 
            SUBROUTINE RESTRICT_MASK_FINE_REVERSE(IFINELEVEL)
              INTEGER(KIND=4), INTENT(IN) :: IFINELEVEL
            END SUBROUTINE RESTRICT_MASK_FINE_REVERSE
          END INTERFACE 
        END MODULE RESTRICT_MASK_FINE_REVERSE__genmod
