        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:18 2017
        MODULE RESTRICT_RESIDUAL_COARSE_REVERSE__genmod
          INTERFACE 
            SUBROUTINE RESTRICT_RESIDUAL_COARSE_REVERSE(IFINELEVEL)
              INTEGER(KIND=4), INTENT(IN) :: IFINELEVEL
            END SUBROUTINE RESTRICT_RESIDUAL_COARSE_REVERSE
          END INTERFACE 
        END MODULE RESTRICT_RESIDUAL_COARSE_REVERSE__genmod
