        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:05 2017
        MODULE RHO_FROM_CURRENT_LEVEL__genmod
          INTERFACE 
            SUBROUTINE RHO_FROM_CURRENT_LEVEL(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE RHO_FROM_CURRENT_LEVEL
          END INTERFACE 
        END MODULE RHO_FROM_CURRENT_LEVEL__genmod
