        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:12 2017
        MODULE RHO_ONLY_LEVEL__genmod
          INTERFACE 
            SUBROUTINE RHO_ONLY_LEVEL(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE RHO_ONLY_LEVEL
          END INTERFACE 
        END MODULE RHO_ONLY_LEVEL__genmod
