        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:21 2017
        MODULE RT_GODUNOV_FINE__genmod
          INTERFACE 
            SUBROUTINE RT_GODUNOV_FINE(ILEVEL,DT)
              INTEGER(KIND=4) :: ILEVEL
              REAL(KIND=8) :: DT
            END SUBROUTINE RT_GODUNOV_FINE
          END INTERFACE 
        END MODULE RT_GODUNOV_FINE__genmod
