        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:21 2017
        MODULE RT_HYDRO_FLAG__genmod
          INTERFACE 
            SUBROUTINE RT_HYDRO_FLAG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE RT_HYDRO_FLAG
          END INTERFACE 
        END MODULE RT_HYDRO_FLAG__genmod
