        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:20 2017
        MODULE RT_INIT_FLOW_FINE__genmod
          INTERFACE 
            SUBROUTINE RT_INIT_FLOW_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE RT_INIT_FLOW_FINE
          END INTERFACE 
        END MODULE RT_INIT_FLOW_FINE__genmod
