        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:20 2017
        MODULE RT_INIT_XION__genmod
          INTERFACE 
            SUBROUTINE RT_INIT_XION(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE RT_INIT_XION
          END INTERFACE 
        END MODULE RT_INIT_XION__genmod
