        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:20 2017
        MODULE RT_INIT_XION_VSWEEP__genmod
          INTERFACE 
            SUBROUTINE RT_INIT_XION_VSWEEP(IND_GRID,NGRID)
              INTEGER(KIND=4) :: IND_GRID(1:)
              INTEGER(KIND=4) :: NGRID
            END SUBROUTINE RT_INIT_XION_VSWEEP
          END INTERFACE 
        END MODULE RT_INIT_XION_VSWEEP__genmod
