        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:20 2017
        MODULE RT_INIT__genmod
          INTERFACE 
            SUBROUTINE RT_INIT
            END SUBROUTINE RT_INIT
          END INTERFACE 
        END MODULE RT_INIT__genmod
