        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:20 2017
        MODULE RT_INIT_FLOW__genmod
          INTERFACE 
            SUBROUTINE RT_INIT_FLOW
            END SUBROUTINE RT_INIT_FLOW
          END INTERFACE 
        END MODULE RT_INIT_FLOW__genmod
