        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:21 2017
        MODULE RT_INTERPOL_HYDRO__genmod
          INTERFACE 
            SUBROUTINE RT_INTERPOL_HYDRO(U1,U2,NN)
              REAL(KIND=8) :: U1(1:,0:,1:)
              REAL(KIND=8) :: U2(1:,1:,1:)
              INTEGER(KIND=4) :: NN
            END SUBROUTINE RT_INTERPOL_HYDRO
          END INTERFACE 
        END MODULE RT_INTERPOL_HYDRO__genmod
