        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:20 2017
        MODULE RT_INIT_HYDRO__genmod
          INTERFACE 
            SUBROUTINE RT_INIT_HYDRO
            END SUBROUTINE RT_INIT_HYDRO
          END INTERFACE 
        END MODULE RT_INIT_HYDRO__genmod
