        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:22 2017
        MODULE RT_MAKE_BOUNDARY_HYDRO__genmod
          INTERFACE 
            SUBROUTINE RT_MAKE_BOUNDARY_HYDRO(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE RT_MAKE_BOUNDARY_HYDRO
          END INTERFACE 
        END MODULE RT_MAKE_BOUNDARY_HYDRO__genmod
