        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:21 2017
        MODULE RT_SET_UNEW__genmod
          INTERFACE 
            SUBROUTINE RT_SET_UNEW(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE RT_SET_UNEW
          END INTERFACE 
        END MODULE RT_SET_UNEW__genmod
