        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:22 2017
        MODULE RT_UNITS__genmod
          INTERFACE 
            SUBROUTINE RT_UNITS(SCALE_NP,SCALE_FP)
              REAL(KIND=8) :: SCALE_NP
              REAL(KIND=8) :: SCALE_FP
            END SUBROUTINE RT_UNITS
          END INTERFACE 
        END MODULE RT_UNITS__genmod
