        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:12 2017
        MODULE SADDLEPOINT_SEARCH__genmod
          INTERFACE 
            SUBROUTINE SADDLEPOINT_SEARCH(XX)
              USE AMR_COMMONS
              REAL(KIND=8) :: XX(1:NCOARSE+NGRIDMAX*8)
            END SUBROUTINE SADDLEPOINT_SEARCH
          END INTERFACE 
        END MODULE SADDLEPOINT_SEARCH__genmod
