        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE SAVEGADGET__genmod
          INTERFACE 
            SUBROUTINE SAVEGADGET(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE SAVEGADGET
          END INTERFACE 
        END MODULE SAVEGADGET__genmod
