        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:39 2017
        MODULE SCATTERING_ANA__genmod
          INTERFACE 
            FUNCTION SCATTERING_ANA(DENS,TP,TR,IGROUP)
              REAL(KIND=8), INTENT(IN) :: DENS
              REAL(KIND=8), INTENT(IN) :: TP
              REAL(KIND=8), INTENT(IN) :: TR
              INTEGER(KIND=4), INTENT(IN) :: IGROUP
              REAL(KIND=8) :: SCATTERING_ANA
            END FUNCTION SCATTERING_ANA
          END INTERFACE 
        END MODULE SCATTERING_ANA__genmod
