        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:53 2017
        MODULE SET_UOLD__genmod
          INTERFACE 
            SUBROUTINE SET_UOLD(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE SET_UOLD
          END INTERFACE 
        END MODULE SET_UOLD__genmod
