        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:22 2017
        MODULE SET_SIGNAL_HANDLER__genmod
          INTERFACE 
            SUBROUTINE SET_SIGNAL_HANDLER
            END SUBROUTINE SET_SIGNAL_HANDLER
          END INTERFACE 
        END MODULE SET_SIGNAL_HANDLER__genmod
