        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:09 2017
        MODULE SET_UNEW_SINK__genmod
          INTERFACE 
            SUBROUTINE SET_UNEW_SINK(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE SET_UNEW_SINK
          END INTERFACE 
        END MODULE SET_UNEW_SINK__genmod
