        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:18 2017
        MODULE SET_SCAN_FLAG_FINE__genmod
          INTERFACE 
            SUBROUTINE SET_SCAN_FLAG_FINE(ILEVEL)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
            END SUBROUTINE SET_SCAN_FLAG_FINE
          END INTERFACE 
        END MODULE SET_SCAN_FLAG_FINE__genmod
