        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:10 2017
        MODULE SET_UOLD_SINK__genmod
          INTERFACE 
            SUBROUTINE SET_UOLD_SINK(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE SET_UOLD_SINK
          END INTERFACE 
        END MODULE SET_UOLD_SINK__genmod
