        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:51 2017
        MODULE SET_MOVIE_VARS__genmod
          INTERFACE 
            SUBROUTINE SET_MOVIE_VARS
            END SUBROUTINE SET_MOVIE_VARS
          END INTERFACE 
        END MODULE SET_MOVIE_VARS__genmod
