        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:15 2017
        MODULE SINK_RT_FEEDBACK__genmod
          INTERFACE 
            SUBROUTINE SINK_RT_FEEDBACK(ILEVEL,DT)
              USE PM_COMMONS
              INTEGER(KIND=4) :: ILEVEL
              REAL(KIND=8) :: DT
            END SUBROUTINE SINK_RT_FEEDBACK
          END INTERFACE 
        END MODULE SINK_RT_FEEDBACK__genmod
