        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE SMOOTH_FINE__genmod
          INTERFACE 
            SUBROUTINE SMOOTH_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE SMOOTH_FINE
          END INTERFACE 
        END MODULE SMOOTH_FINE__genmod
