        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:50 2017
        MODULE SOUNDSPEED_EOS__genmod
          INTERFACE 
            SUBROUTINE SOUNDSPEED_EOS(RHO_TEMP,ENINT_TEMP,CSEOS)
              REAL(KIND=8), INTENT(IN) :: RHO_TEMP
              REAL(KIND=8), INTENT(IN) :: ENINT_TEMP
              REAL(KIND=8), INTENT(OUT) :: CSEOS
            END SUBROUTINE SOUNDSPEED_EOS
          END INTERFACE 
        END MODULE SOUNDSPEED_EOS__genmod
