        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:08 2017
        MODULE STAR_FORMATION__genmod
          INTERFACE 
            SUBROUTINE STAR_FORMATION(ILEVEL)
              USE AMR_COMMONS
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE STAR_FORMATION
          END INTERFACE 
        END MODULE STAR_FORMATION__genmod
