        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE SURFACE_INT_NP__genmod
          INTERFACE 
            SUBROUTINE SURFACE_INT_NP(IND_CELL,NP,ILEVEL)
              INTEGER(KIND=4) :: IND_CELL(1:)
              INTEGER(KIND=4) :: NP
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE SURFACE_INT_NP
          END INTERFACE 
        END MODULE SURFACE_INT_NP__genmod
