        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE SURFACE_INT__genmod
          INTERFACE 
            SUBROUTINE SURFACE_INT
            END SUBROUTINE SURFACE_INT
          END INTERFACE 
        END MODULE SURFACE_INT__genmod
