        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:00 2017
        MODULE SYNCHRO_HYDRO_FINE__genmod
          INTERFACE 
            SUBROUTINE SYNCHRO_HYDRO_FINE(ILEVEL,DTEFF)
              INTEGER(KIND=4) :: ILEVEL
              REAL(KIND=8) :: DTEFF
            END SUBROUTINE SYNCHRO_HYDRO_FINE
          END INTERFACE 
        END MODULE SYNCHRO_HYDRO_FINE__genmod
