        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:06 2017
        MODULE SYNCHRO_FINE_STATIC__genmod
          INTERFACE 
            SUBROUTINE SYNCHRO_FINE_STATIC(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE SYNCHRO_FINE_STATIC
          END INTERFACE 
        END MODULE SYNCHRO_FINE_STATIC__genmod
