        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:59 2017
        MODULE SYNCHYDROFINE1__genmod
          INTERFACE 
            SUBROUTINE SYNCHYDROFINE1(IND_CELL,NCELL,DTEFF)
              INTEGER(KIND=4) :: IND_CELL(1:)
              INTEGER(KIND=4) :: NCELL
              REAL(KIND=8) :: DTEFF
            END SUBROUTINE SYNCHYDROFINE1
          END INTERFACE 
        END MODULE SYNCHYDROFINE1__genmod
