        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:06 2017
        MODULE SYNCHRO_FINE__genmod
          INTERFACE 
            SUBROUTINE SYNCHRO_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE SYNCHRO_FINE
          END INTERFACE 
        END MODULE SYNCHRO_FINE__genmod
