        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:00 2017
        MODULE TABULATE_ART4__genmod
          INTERFACE 
            SUBROUTINE TABULATE_ART4
            END SUBROUTINE TABULATE_ART4
          END INTERFACE 
        END MODULE TABULATE_ART4__genmod
