        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:50 2017
        MODULE TEMPERATURE_EOS__genmod
          INTERFACE 
            SUBROUTINE TEMPERATURE_EOS(RHO_TEMP,ENINT_TEMP,TEOS,HT)
              REAL(KIND=8), INTENT(IN) :: RHO_TEMP
              REAL(KIND=8), INTENT(IN) :: ENINT_TEMP
              REAL(KIND=8), INTENT(OUT) :: TEOS
              INTEGER(KIND=4), INTENT(OUT) :: HT
            END SUBROUTINE TEMPERATURE_EOS
          END INTERFACE 
        END MODULE TEMPERATURE_EOS__genmod
