        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE TEST_FLAG__genmod
          INTERFACE 
            SUBROUTINE TEST_FLAG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE TEST_FLAG
          END INTERFACE 
        END MODULE TEST_FLAG__genmod
