        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:11 2017
        MODULE THERMAL_FEEDBACK__genmod
          INTERFACE 
            SUBROUTINE THERMAL_FEEDBACK(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE THERMAL_FEEDBACK
          END INTERFACE 
        END MODULE THERMAL_FEEDBACK__genmod
