        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE TRIM_CLUMPS__genmod
          INTERFACE 
            SUBROUTINE TRIM_CLUMPS
            END SUBROUTINE TRIM_CLUMPS
          END INTERFACE 
        END MODULE TRIM_CLUMPS__genmod
