        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:05 2017
        MODULE TSC_FROM_MULTIPOLE__genmod
          INTERFACE 
            SUBROUTINE TSC_FROM_MULTIPOLE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE TSC_FROM_MULTIPOLE
          END INTERFACE 
        END MODULE TSC_FROM_MULTIPOLE__genmod
