        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:09 2017
        MODULE UPD_CLOUD__genmod
          INTERFACE 
            SUBROUTINE UPD_CLOUD(IND_PART,NP)
              INTEGER(KIND=4) :: IND_PART(1:)
              INTEGER(KIND=4) :: NP
            END SUBROUTINE UPD_CLOUD
          END INTERFACE 
        END MODULE UPD_CLOUD__genmod
