        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:09 2017
        MODULE UPDATE_SINK__genmod
          INTERFACE 
            SUBROUTINE UPDATE_SINK(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE UPDATE_SINK
          END INTERFACE 
        END MODULE UPDATE_SINK__genmod
