        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:41 2017
        MODULE UPDATERTGROUPS_COOLCONSTANTS__genmod
          INTERFACE 
            SUBROUTINE UPDATERTGROUPS_COOLCONSTANTS
            END SUBROUTINE UPDATERTGROUPS_COOLCONSTANTS
          END INTERFACE 
        END MODULE UPDATERTGROUPS_COOLCONSTANTS__genmod
