        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE UPDATE_TIME__genmod
          INTERFACE 
            SUBROUTINE UPDATE_TIME(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE UPDATE_TIME
          END INTERFACE 
        END MODULE UPDATE_TIME__genmod
