        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:57 2017
        MODULE UPL_LEFT__genmod
          INTERFACE 
            SUBROUTINE UPL_LEFT(IND_CELL,IGRID_SON,IDIM,NCELL)
              INTEGER(KIND=4) :: IND_CELL(1:)
              INTEGER(KIND=4) :: IGRID_SON(1:)
              INTEGER(KIND=4) :: IDIM
              INTEGER(KIND=4) :: NCELL
            END SUBROUTINE UPL_LEFT
          END INTERFACE 
        END MODULE UPL_LEFT__genmod
