        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:46 2017
        MODULE USERFLAG_FINE__genmod
          INTERFACE 
            SUBROUTINE USERFLAG_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE USERFLAG_FINE
          END INTERFACE 
        END MODULE USERFLAG_FINE__genmod
