        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE VIRTUAL_SADDLE_MAX__genmod
          INTERFACE 
            SUBROUTINE VIRTUAL_SADDLE_MAX
              USE AMR_COMMONS
            END SUBROUTINE VIRTUAL_SADDLE_MAX
          END INTERFACE 
        END MODULE VIRTUAL_SADDLE_MAX__genmod
