        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE VIRTUAL_PEAK_INT__genmod
          INTERFACE 
            SUBROUTINE VIRTUAL_PEAK_INT(XX,ACTION)
              USE CLFIND_COMMONS
              USE AMR_COMMONS
              INTEGER(KIND=4) :: XX(1:NPEAKS_MAX)
              CHARACTER(LEN=3) :: ACTION
            END SUBROUTINE VIRTUAL_PEAK_INT
          END INTERFACE 
        END MODULE VIRTUAL_PEAK_INT__genmod
