        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:07 2017
        MODULE VIRTUAL_TREE_FINE__genmod
          INTERFACE 
            SUBROUTINE VIRTUAL_TREE_FINE(ILEVEL)
              USE AMR_COMMONS
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE VIRTUAL_TREE_FINE
          END INTERFACE 
        END MODULE VIRTUAL_TREE_FINE__genmod
