        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE VIRTUAL_PEAK_DP__genmod
          INTERFACE 
            SUBROUTINE VIRTUAL_PEAK_DP(XX,ACTION)
              USE CLFIND_COMMONS
              USE AMR_COMMONS
              REAL(KIND=8) :: XX(1:NPEAKS_MAX)
              CHARACTER(LEN=3) :: ACTION
            END SUBROUTINE VIRTUAL_PEAK_DP
          END INTERFACE 
        END MODULE VIRTUAL_PEAK_DP__genmod
