        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:45 2017
        MODULE WALLCLOCK__genmod
          INTERFACE 
            FUNCTION WALLCLOCK
              REAL(KIND=8) :: WALLCLOCK
            END FUNCTION WALLCLOCK
          END INTERFACE 
        END MODULE WALLCLOCK__genmod
