        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE WRITE_CLUMP_MAP__genmod
          INTERFACE 
            SUBROUTINE WRITE_CLUMP_MAP
            END SUBROUTINE WRITE_CLUMP_MAP
          END INTERFACE 
        END MODULE WRITE_CLUMP_MAP__genmod
