        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:52 2017
        MODULE WRITE_SCREEN__genmod
          INTERFACE 
            SUBROUTINE WRITE_SCREEN
            END SUBROUTINE WRITE_SCREEN
          END INTERFACE 
        END MODULE WRITE_SCREEN__genmod
