        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:44 2017
        MODULE WRITE_GITINFO__genmod
          INTERFACE 
            SUBROUTINE WRITE_GITINFO
            END SUBROUTINE WRITE_GITINFO
          END INTERFACE 
        END MODULE WRITE_GITINFO__genmod
