        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:20 2017
        MODULE WRITE_GROUP_PROPS__genmod
          INTERFACE 
            SUBROUTINE WRITE_GROUP_PROPS(UPDATE,LUN)
              LOGICAL(KIND=4) :: UPDATE
              INTEGER(KIND=4) :: LUN
            END SUBROUTINE WRITE_GROUP_PROPS
          END INTERFACE 
        END MODULE WRITE_GROUP_PROPS__genmod
