        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:14:45 2017
        MODULE WRITEMEM__genmod
          INTERFACE 
            SUBROUTINE WRITEMEM(USEDMEM)
              REAL(KIND=4) :: USEDMEM
            END SUBROUTINE WRITEMEM
          END INTERFACE 
        END MODULE WRITEMEM__genmod
