        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 22 21:15:13 2017
        MODULE WRITE_CLUMP_PROPERTIES__genmod
          INTERFACE 
            SUBROUTINE WRITE_CLUMP_PROPERTIES(TO_FILE)
              USE CLFIND_COMMONS
              LOGICAL(KIND=4) :: TO_FILE
            END SUBROUTINE WRITE_CLUMP_PROPERTIES
          END INTERFACE 
        END MODULE WRITE_CLUMP_PROPERTIES__genmod
